// Code generated by command: go run asm.go -out out/polyval_amd64.s -stubs out/stub_amd64.go -pkg polyval. DO NOT EDIT.

//go:build gc && !purego

#include "textflag.h"

// func ctmulAsm(z *fieldElement, x uint64, y uint64)
// Requires: PCLMULQDQ, SSE2
TEXT ·ctmulAsm(SB), NOSPLIT, $0-24
	MOVQ      z+0(FP), AX
	MOVQ      x+8(FP), X0
	MOVQ      y+16(FP), X1
	PCLMULQDQ $0x00, X0, X1
	MOVOU     X1, (AX)
	RET
