// Code generated by command: go run asm.go -out out/polyval_amd64.s -stubs out/stub_amd64.go -pkg polyval. DO NOT EDIT.

//go:build gc && !purego

package polyval

//go:noescape
func polymulAsm(acc *fieldElement, key *fieldElement)

//go:noescape
func polymulBlocksAsm(acc *fieldElement, pow *[8]fieldElement, input *byte, nblocks int)
