// Code generated by command: go run asm.go -out out/polyval_amd64.s -stubs out/stub_amd64.go -pkg polyval. DO NOT EDIT.

//go:build gc && !purego

package polyval

//go:noescape
func ctmulAsm(z *fieldElement, x uint64, y uint64)
